# OpenTelemetry Operator - manages OTEL Collectors via CRD
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  - name: kube-prometheus-stack
    namespace: monitoring

  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system

  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-contrib
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Enable admission webhooks
    admissionWebhooks:
      certManager:
        enabled: true
