apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:

  dependsOn:
  - name: flux-system

  interval: 5m
  path: ./flux-repo/clusters/production/infrastructure/namespaces
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
