apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  dependsOn:
  - name: monitoring

  interval: 5m
  path: ./flux-repo/cluster/otel-collector
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
