# ServiceMonitor for kbot metrics
# Requires kbot to expose /metrics endpoint on port 8080
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kbot
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kbot
  namespaceSelector:
    matchNames:
    - demo
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
# PodMonitor as alternative if no Service exists
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kbot
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kbot
  namespaceSelector:
    matchNames:
    - demo
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
